os: linux

dist: xenial

group: stable

language: python 

python:
        - 3.5

before_install:
        # install R
        - sudo echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list
        - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
        - gpg -a --export E084DAB9 | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get install r-base r-base-dev

install: pip3 install pfla

script: python3 pfla/test.py


